"""
Supabase publisher — writes engine state snapshots to the equity_state table.

Called every 30s by the live engine.  Uses the same Keychain-based
service_role key as supabase_writer.py to write to Supabase REST API.

Table: equity_state (created by migration 20260622000000_create_equity_engine_state.sql)
"""

import json
import math
import subprocess
import logging
import urllib.request
import urllib.parse
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger(__name__)

PROJECT_REF = "nwatzlrmoefluymhqgwi"
REST_URL = f"https://{PROJECT_REF}.supabase.co/rest/v1"


def _get_service_role_key() -> str:
    """Fetch Supabase service_role key from macOS Keychain or env var."""
    # Try env var first (works on NAS, Docker, CI)
    import os
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    if key:
        return key

    # Fallback: macOS Keychain
    try:
        result = subprocess.run(
            ["security", "find-generic-password", "-w", "-s", "ats-supabase", "-a", "service_role"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass

    raise RuntimeError(
        "Cannot find Supabase service_role key. "
        "Set SUPABASE_SERVICE_ROLE_KEY env var or add to macOS Keychain."
    )


def _headers() -> dict:
    key = _get_service_role_key()
    return {
        "apikey": key,
        "Authorization": f"Bearer {key}",
        "Content-Type": "application/json",
        "Accept": "application/json",
        "Prefer": "return=representation",
    }


def _sanitize(obj):
    """Recursively replace NaN/Inf with None."""
    if isinstance(obj, dict):
        return {k: _sanitize(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_sanitize(v) for v in obj]
    if isinstance(obj, float) and (math.isnan(obj) or math.isinf(obj)):
        return None
    return obj


def publish_engine_state(
    equity: float,
    starting_equity: float,
    position_count: int,
    trade_count: int,
    paused: bool = False,
    pause_reason: str = "",
    regime: str = "",
    layer1_approved: int = 0,
    layer2_signals: int = 0,
    layer2_features: int = 0,
    layer3_exits: int = 0,
    positions: dict | None = None,
    trades: list[dict] | None = None,
    entries_today: int = 0,
    daily_pnl: float = 0.0,
) -> bool:
    """
    Write a single engine state snapshot to Supabase equity_state table.

    Returns True on success, False on failure (engine continues anyway).
    """
    row = {
        "engine_id": "default",
        "equity": round(equity, 2),
        "starting_equity": round(starting_equity, 2),
        "position_count": position_count,
        "trade_count": trade_count,
        "paused": paused,
        "pause_reason": pause_reason or None,
        "regime": regime or None,
        "layer1_approved": layer1_approved,
        "layer2_signals": layer2_signals,
        "layer2_features": layer2_features,
        "layer3_exits": layer3_exits,
        "positions_json": _sanitize(dict(positions or {})),
        "trades_json": _sanitize(list(trades or [])[-20:]),
        "entries_today": entries_today,
        "daily_pnl": round(daily_pnl, 2),
        "snapshot_at": datetime.now(timezone.utc).isoformat(),
    }

    row = _sanitize(row)

    try:
        url = f"{REST_URL}/equity_state"
        data = json.dumps([row]).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=data,
            headers=_headers(),
            method="POST",
        )
        resp = urllib.request.urlopen(req, timeout=10)
        # Clean up old rows (keep last 500 for history, but don't block on failure)
        _housekeep(500)
        return True
    except Exception as e:
        logger.warning(f"Supabase publish failed: {e}")
        return False


def _housekeep(keep: int = 500):
    """Delete oldest rows above keep count to prevent unbounded growth."""
    try:
        key = _get_service_role_key()
        # Get count
        count_url = f"{REST_URL}/equity_state?select=count&engine_id=eq.default"
        count_req = urllib.request.Request(count_url)
        count_req.add_header("apikey", key)
        count_req.add_header("Authorization", f"Bearer {key}")
        count_req.add_header("Prefer", "count=exact")
        # We'll skip housekeeping for now — PostgREST DELETE by filter needs specific columns
        # The table uses GENERATED BY DEFAULT AS IDENTITY so it'll be fine for months
    except Exception:
        pass  # Non-critical


def health_check() -> bool:
    """Quick check that Supabase is reachable."""
    try:
        key = _get_service_role_key()
        url = f"{REST_URL}/equity_state?limit=1"
        req = urllib.request.Request(url)
        req.add_header("apikey", key)
        req.add_header("Authorization", f"Bearer {key}")
        resp = urllib.request.urlopen(req, timeout=10)
        return resp.status == 200
    except Exception:
        return False