"""
Supabase publisher — writes engine state snapshots to the equity_state table.

Called every 30s by the live engine.  Uses the same Keychain-based
service_role key as supabase_writer.py to write to Supabase REST API.

Table: equity_state (created by migration 20260622000000_create_equity_engine_state.sql)
"""

import json
import math
import subprocess
import logging
import urllib.request
import urllib.parse
from datetime import datetime, timezone
from typing import Optional

logger = logging.getLogger(__name__)

PROJECT_REF = "nwatzlrmoefluymhqgwi"
REST_URL = f"https://{PROJECT_REF}.supabase.co/rest/v1"


def _get_service_role_key() -> str:
    """Fetch Supabase service_role key from macOS Keychain or env var."""
    # Try env var first (works on NAS, Docker, CI)
    import os
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    if key:
        return key

    # Fallback: macOS Keychain
    try:
        result = subprocess.run(
            ["security", "find-generic-password", "-w", "-s", "ats-supabase", "-a", "service_role"],
            capture_output=True, text=True, timeout=10,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass

    raise RuntimeError(
        "Cannot find Supabase service_role key. "
        "Set SUPABASE_SERVICE_ROLE_KEY env var or add to macOS Keychain."
    )


def _headers() -> dict:
    key = _get_service_role_key()
    return {
        "apikey": key,
        "Authorization": f"Bearer {key}",
        "Content-Type": "application/json",
        "Accept": "application/json",
        "Prefer": "return=representation",
    }


def _sanitize(obj):
    """Recursively replace NaN/Inf with None."""
    if isinstance(obj, dict):
        return {k: _sanitize(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_sanitize(v) for v in obj]
    if isinstance(obj, float) and (math.isnan(obj) or math.isinf(obj)):
        return None
    return obj


def publish_engine_state(
    equity: float,
    starting_equity: float,
    position_count: int,
    trade_count: int,
    paused: bool = False,
    pause_reason: str = "",
    regime: str = "",
    layer1_approved: int = 0,
    layer2_signals: int = 0,
    layer2_features: int = 0,
    layer3_exits: int = 0,
    positions: dict | None = None,
    trades: list[dict] | None = None,
    entries_today: int = 0,
    daily_pnl: float = 0.0,
) -> bool:
    """
    Write a single engine state snapshot to Supabase equity_state table.

    Returns True on success, False on failure (engine continues anyway).
    """
    row = {
        "engine_id": "default",
        "equity": round(equity, 2),
        "starting_equity": round(starting_equity, 2),
        "position_count": position_count,
        "trade_count": trade_count,
        "paused": paused,
        "pause_reason": pause_reason or None,
        "regime": regime or None,
        "layer1_approved": layer1_approved,
        "layer2_signals": layer2_signals,
        "layer2_features": layer2_features,
        "layer3_exits": layer3_exits,
        "positions_json": _sanitize(dict(positions or {})),
        "trades_json": _sanitize(list(trades or [])[-20:]),
        "entries_today": entries_today,
        "daily_pnl": round(daily_pnl, 2),
        "snapshot_at": datetime.now(timezone.utc).isoformat(),
    }

    row = _sanitize(row)

    try:
        url = f"{REST_URL}/equity_state"
        data = json.dumps([row]).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=data,
            headers=_headers(),
            method="POST",
        )
        resp = urllib.request.urlopen(req, timeout=10)
        # Clean up old rows (keep last 500 for history, but don't block on failure)
        _housekeep(500)
        return True
    except Exception as e:
        logger.warning(f"Supabase publish failed: {e}")
        return False


def _housekeep(keep: int = 500):
    """Delete oldest rows above keep count to prevent unbounded growth."""
    try:
        key = _get_service_role_key()
        # Get count
        count_url = f"{REST_URL}/equity_state?select=count&engine_id=eq.default"
        count_req = urllib.request.Request(count_url)
        count_req.add_header("apikey", key)
        count_req.add_header("Authorization", f"Bearer {key}")
        count_req.add_header("Prefer", "count=exact")
        # We'll skip housekeeping for now — PostgREST DELETE by filter needs specific columns
        # The table uses GENERATED BY DEFAULT AS IDENTITY so it'll be fine for months
    except Exception:
        pass  # Non-critical


def publish_activity(
    event_type: str,
    message: str,
    symbol: str | None = None,
    detail: dict | None = None,
) -> bool:
    """
    Publish a single significant event to the equity_activity table.
    Used for the live activity feed on the Vercel dashboard.
    
    Args:
        event_type: signal_fired / entry_blocked / entry_confirmed / 
                    exit_triggered / regime_change / engine_started /
                    engine_paused / engine_resumed
        message: Human-readable description
        symbol: Ticker symbol (nullable for engine/regime events)
        detail: Extra structured data (prob, price, reason, etc.)
    
    Returns True on success, False on failure (fire-and-forget).
    """
    row = {
        "event_type": event_type,
        "symbol": symbol,
        "message": message,
        "detail_json": _sanitize(detail or {}),
    }
    
    try:
        url = f"{REST_URL}/equity_activity"
        data = json.dumps(row).encode("utf-8")
        req = urllib.request.Request(
            url,
            data=data,
            headers=_headers(),
            method="POST",
        )
        urllib.request.urlopen(req, timeout=5)
        return True
    except Exception as e:
        logger.debug(f"Activity publish failed: {e}")
        return False


def upsert_shortlist(
    symbol: str,
    current_price: float | None = None,
    sma200: float | None = None,
    price_vs_sma200_pct: float | None = None,
    xgb_prob: float | None = None,
    prob_vs_threshold: float | None = None,
    rsi_14: float | None = None,
    atr_pct: float | None = None,
    vwap_distance_pct: float | None = None,
    volume_zscore: float | None = None,
    approved: bool = False,
    status: str = "evaluating",
    block_reason: str | None = None,
    recent_snapshots: list[dict] | None = None,
) -> bool:
    """
    Upsert a single symbol's shortlist data into equity_shortlist.
    Uses POST with Prefer: resolution=merge-duplicates so one row per symbol.
    
    Returns True on success.
    """
    row = {
        "symbol": symbol,
        "current_price": round(current_price, 2) if current_price is not None else None,
        "sma200": round(sma200, 2) if sma200 is not None else None,
        "price_vs_sma200_pct": round(price_vs_sma200_pct, 2) if price_vs_sma200_pct is not None else None,
        "xgb_prob": round(xgb_prob, 4) if xgb_prob is not None else None,
        "prob_vs_threshold": round(prob_vs_threshold, 4) if prob_vs_threshold is not None else None,
        "rsi_14": round(rsi_14, 2) if rsi_14 is not None else None,
        "atr_pct": round(atr_pct, 4) if atr_pct is not None else None,
        "vwap_distance_pct": round(vwap_distance_pct, 4) if vwap_distance_pct is not None else None,
        "volume_zscore": round(volume_zscore, 2) if volume_zscore is not None else None,
        "approved": approved,
        "status": status,
        "block_reason": block_reason or None,
        "recent_snapshots": _sanitize(list(recent_snapshots or [])[-10:]),
        "last_evaluated": datetime.now(timezone.utc).isoformat(),
        "last_updated": datetime.now(timezone.utc).isoformat(),
    }
    
    row = _sanitize(row)
    
    try:
        url = f"{REST_URL}/equity_shortlist"
        # Use upsert by symbol (unique constraint)
        headers = _headers()
        headers["Prefer"] = "resolution=merge-duplicates"
        data = json.dumps(row).encode("utf-8")
        req = urllib.request.Request(url, data=data, headers=headers, method="POST")
        urllib.request.urlopen(req, timeout=10)
        return True
    except Exception as e:
        logger.debug(f"Shortlist upsert failed for {symbol}: {e}")
        return False


def housekeep_activity(keep: int = 200):
    """Delete oldest activity rows above keep count."""
    try:
        key = _get_service_role_key()
        # Get IDs to delete
        url = (f"{REST_URL}/equity_activity"
               f"?select=id&order=created_at.desc&limit=100000&offset=0")
        req = urllib.request.Request(url)
        req.add_header("apikey", key)
        req.add_header("Authorization", f"Bearer {key}")
        resp = urllib.request.urlopen(req, timeout=10)
        rows = json.loads(resp.read())
        if len(rows) > keep:
            ids_to_delete = [r["id"] for r in rows[keep:]]
            for batch_start in range(0, len(ids_to_delete), 50):
                batch = ids_to_delete[batch_start:batch_start + 50]
                ids_filter = ",".join(f"eq.{bid}" for bid in batch)
                del_url = f"{REST_URL}/equity_activity?id=in.({','.join(str(x) for x in batch)})"
                del_req = urllib.request.Request(del_url, method="DELETE")
                del_req.add_header("apikey", key)
                del_req.add_header("Authorization", f"Bearer {key}")
                urllib.request.urlopen(del_req, timeout=15)
    except Exception:
        pass  # Non-critical


def health_check() -> bool:
    """Quick check that Supabase is reachable."""
    try:
        key = _get_service_role_key()
        url = f"{REST_URL}/equity_state?limit=1"
        req = urllib.request.Request(url)
        req.add_header("apikey", key)
        req.add_header("Authorization", f"Bearer {key}")
        resp = urllib.request.urlopen(req, timeout=10)
        return resp.status == 200
    except Exception:
        return False
