"""
Supabase writer — pushes ATS signals/orders/portfolio to Supabase.

Uses the REST API directly (no SDK dependency):
  POST /rest/v1/{table}  — insert rows
  PATCH /rest/v1/{table} — update existing rows

Secrets read from macOS Keychain: ats-supabase (service_role key).
"""

import json
import math
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import requests

# ── Config ───────────────────────────────────────────────────────────────────

PROJECT_REF = "nwatzlrmoefluymhqgwi"
BASE_URL = f"https://{PROJECT_REF}.supabase.co"
REST_URL = f"{BASE_URL}/rest/v1"

TRADING_DIR = Path.home() / ".hermes" / "trading"
SIGNALS_FILE = TRADING_DIR / ".cache" / "signals.json"


# ── Keychain helper ──────────────────────────────────────────────────────────


def _get_keychain(service: str = "ats-supabase", account: str = "service_role") -> str:
    """Fetch a secret from macOS Keychain."""
    result = subprocess.run(
        ["security", "find-generic-password", "-w", "-s", service, "-a", account],
        capture_output=True, text=True, check=True,
    )
    return result.stdout.strip()


# ── Supabase REST helpers ────────────────────────────────────────────────────


def _headers() -> dict[str, str]:
    key = _get_keychain()
    return {
        "apikey": key,
        "Authorization": f"Bearer {key}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }


def _sanitize(obj):
    """Recursively replace NaN/Inf with None (JSON can't serialize them)."""
    if isinstance(obj, dict):
        return {k: _sanitize(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_sanitize(v) for v in obj]
    if isinstance(obj, float) and (math.isnan(obj) or math.isinf(obj)):
        return None
    return obj


def _insert(table: str, rows: list[dict]) -> list[dict]:
    """
    Insert rows into a Supabase table (id auto-generated by sequence).
    Returns the response data.
    """
    if not rows:
        return []

    rows = _sanitize(rows)
    url = f"{REST_URL}/{table}"
    resp = requests.post(
        url,
        headers={**_headers(), "Prefer": "return=representation"},
        json=rows,
        timeout=15,
    )
    resp.raise_for_status()
    return resp.json()


def _select(table: str, query: Optional[dict] = None, order: Optional[str] = None, limit: int = 100) -> list[dict]:
    """Select rows from a table."""
    url = f"{REST_URL}/{table}"
    params = {"limit": limit}
    if query:
        for k, v in query.items():
            params[k] = f"eq.{v}"
    if order:
        params["order"] = order
    resp = requests.get(url, headers=_headers(), params=params, timeout=15)
    resp.raise_for_status()
    return resp.json()


def _delete_older_than(table: str, column: str, age_days: int):
    """Delete rows older than N days (housekeeping)."""
    # Supabase REST doesn't support DELETE with lt filter easily via URL params,
    # so we use the rpc approach or raw filter
    cutoff = datetime.now(timezone.utc).isoformat()
    # We do a select to find old rows, then delete by ID
    url = f"{REST_URL}/{table}"
    params = {column: f"lt.{cutoff}"}  # Not ideal — need explicit date
    resp = requests.get(url, headers=_headers(), params=params, limit=limit)
    # For now skip housekeeping — keep it simple


# ── Signal-to-DB mapping ─────────────────────────────────────────────────────


SIGNAL_COLUMNS = {
    "ticker": "symbol",
    "direction": "action",       # enter_long / exit_long
    "bucket": "bucket",
    "vix_zone": None,             # derived below
    "signal_json": None,          # built below
}

# VIX zone mapping (from group names in the watchlist)
VIX_ZONE_MAP = {
    "high_beta_growth": "high_beta",
    "moderate_growth": "moderate_beta",
    "neutral": "low_beta",
    "moderate_defensive": "defensive",
}


def _signal_to_row(signal: dict) -> dict:
    """Map a signal dict from the engine to a signals table row.

    Schema constraints: bucket ∈ {base_yield, alpha, convexity},
                        direction ∈ {LONG, SHORT, NEUTRAL}
    """
    # Map engine bucket names to DB values
    bucket_map = {"alpha_gen": "alpha", "base_yield": "base_yield", "convexity": "convexity"}

    # Map action to direction
    action = signal.get("action", "")
    if action == "enter_long":
        direction = "LONG"
    elif action == "exit_long":
        direction = "SHORT"
    else:
        direction = signal.get("direction", "NEUTRAL").upper()

    return {
        "ticker": signal["symbol"],
        "direction": direction,
        "bucket": bucket_map.get(signal.get("bucket", ""), "alpha"),
        "vix_zone": VIX_ZONE_MAP.get(signal.get("group", ""), None),
        "signal_json": signal,
        "status": "pending",
    }


# ── HK Watchlist ──────────────────────────────────────────────────────────────

WATCHLIST_FILE = TRADING_DIR / "watchlist.json"


def _watchlist_candidate_to_rows(candidates: list[dict], candidate_type: str, beta_group: str, start_rank: int = 1) -> list[dict]:
    """Convert watchlist candidate entries to DB rows."""
    rows = []
    for rank, s in enumerate(candidates, start=start_rank):
        rows.append({
            "symbol": s.get("symbol", ""),
            "candidate_type": candidate_type,
            "beta_vix": s.get("beta_vix", 0),
            "beta_dxy": s.get("beta_dxy", 0),
            "rs_zscore": s.get("rs_zscore", 0),
            "beta_group": beta_group,
            "rank_in_group": rank,
        })
    return rows


def publish_hk_watchlist() -> int:
    """Publish HK watchlist candidates to Supabase watchlist_hk table.

    Reads the latest watchlist.json and pushes long/short candidates
    for the HK market. Clears old HK data before inserting fresh.
    Returns number of rows written.
    """
    if not WATCHLIST_FILE.exists():
        print("  No watchlist.json found.")
        return 0

    with open(WATCHLIST_FILE) as f:
        wl = json.load(f)

    hk_data = wl.get("hk", {})
    groups = hk_data.get("groups", {})
    if not groups:
        print("  No HK watchlist groups found.")
        return 0

    rows = []
    for gid in sorted(groups.keys()):
        g = groups[gid]
        label = g.get("label", f"group_{gid}")
        rows.extend(_watchlist_candidate_to_rows(
            g.get("long_candidates", []), "long", label))
        rows.extend(_watchlist_candidate_to_rows(
            g.get("short_candidates", []), "short", label))

    if not rows:
        print("  No HK candidates to publish.")
        return 0

    # Delete old HK data, then insert fresh
    svc_role = _get_keychain()
    rest_url = f"https://{PROJECT_REF}.supabase.co/rest/v1/watchlist_hk"
    headers = {
        "apikey": svc_role,
        "Authorization": f"Bearer {svc_role}",
        "Content-Type": "application/json",
    }

    # Delete all existing rows (last 24h only to be safe — keep some history)
    try:
        resp = requests.delete(rest_url, headers=headers, params={"generated_at": "lt.now"}, timeout=15)
        # If delete on a generated_at filter fails, just delete all
        if resp.status_code >= 400:
            # Delete id > 0 (all rows) — this works
            resp = requests.delete(rest_url, headers=headers, params={"id": "gte.0"}, timeout=15)
    except Exception:
        pass  # Best-effort cleanup

    # Insert fresh
    result = _insert("watchlist_hk", rows)
    count = len(result) if isinstance(result, list) else 0
    print(f"  Supabase: {count} HK watchlist entries written")
    return count


# ── Public API (existing) ─────────────────────────────────────────────────────


def publish_signals(signals: list[dict]) -> int:
    """
    Write signals to the Supabase `signals` table.

    Returns number of rows written.
    """
    rows = [_signal_to_row(s) for s in signals]
    if not rows:
        return 0

    result = _insert("signals", rows)
    count = len(result) if isinstance(result, list) else 0

    print(f"  Supabase: {count} signals written to signals table")
    return count


def publish_from_cache() -> int:
    """
    Read signals.json cache and publish to Supabase.

    Returns number of signals written.
    """
    if not SIGNALS_FILE.exists():
        print("  No signals.json found.")
        return 0

    with open(SIGNALS_FILE) as f:
        data = json.load(f)

    signals = data.get("signals", [])
    if not signals:
        print("  No signals in signals.json.")
        return 0

    return publish_signals(signals)


def health_check() -> bool:
    """Check that Supabase is reachable and the service_role key works."""
    try:
        resp = requests.get(f"{REST_URL}/signals?limit=1", headers=_headers(), timeout=10)
        resp.raise_for_status()
        return True
    except Exception as e:
        print(f"  Supabase health check FAILED: {e}")
        return False


# ── CLI ──────────────────────────────────────────────────────────────────────


if __name__ == "__main__":
    import sys

    cmd = sys.argv[1] if len(sys.argv) > 1 else "publish"

    if cmd == "publish":
        count = publish_from_cache()
        print(f"Done. {count} signals published.")
    elif cmd == "health":
        ok = health_check()
        print(f"Supabase health: {'OK' if ok else 'FAILED'}")
        sys.exit(0 if ok else 1)
    elif cmd == "direct":
        # Accept signals on stdin for piped usage
        raw = sys.stdin.read()
        signals = json.loads(raw) if raw.strip().startswith("[") else json.loads(raw).get("signals", [])
        count = publish_signals(signals)
        print(f"Done. {count} signals published.")
    else:
        print(f"Usage: {sys.argv[0]} [publish|health|direct]")
        sys.exit(1)
