-- Equity Engine State table for the Vercel dashboard.
-- The engine writes state snapshots every 30 seconds.
-- The Next.js page reads the latest row via Supabase realtime.

CREATE TABLE IF NOT EXISTS equity_state (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  engine_id       TEXT NOT NULL DEFAULT 'default',         -- which engine instance (for multi-engine future)
  equity          DOUBLE PRECISION NOT NULL DEFAULT 100000,
  starting_equity DOUBLE PRECISION NOT NULL DEFAULT 100000,
  position_count  INTEGER NOT NULL DEFAULT 0,
  trade_count     INTEGER NOT NULL DEFAULT 0,
  paused          BOOLEAN NOT NULL DEFAULT FALSE,
  pause_reason    TEXT,
  regime          TEXT,                                   -- risk_on / choppy / risk_off / crisis
  layer1_approved INTEGER NOT NULL DEFAULT 0,             -- stocks passing SMA(200)
  layer2_signals  INTEGER NOT NULL DEFAULT 0,             -- XGBoost probability > threshold
  layer2_features  INTEGER NOT NULL DEFAULT 0,            -- total feature computations
  layer3_exits    INTEGER NOT NULL DEFAULT 0,             -- total exit orders generated
  positions_json  JSONB,                                  -- active positions (symbol → {entry, stop, trail, qty, ...})
  trades_json     JSONB,                                  -- last 20 trade records
  entries_today   INTEGER NOT NULL DEFAULT 0,             -- PDT tracking
  daily_pnl       DOUBLE PRECISION NOT NULL DEFAULT 0,
  snapshot_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Index for fast lookups by engine
CREATE INDEX IF NOT EXISTS idx_equity_state_engine ON equity_state(engine_id, snapshot_at DESC);

-- RLS: anon can read, service_role writes
ALTER TABLE equity_state ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_equity_state" ON equity_state;
CREATE POLICY "anon_select_equity_state" ON equity_state
  FOR SELECT
  TO anon
  USING (true);

-- Enable realtime for live dashboard updates
-- NOTE: If this fails with "publication already exists", the table is already added — ignore error.
ALTER publication supabase_realtime ADD TABLE equity_state;
