-- Create and configure the portfolio table for position tracking.
-- This table holds the user's current positions synced from Longbridge.
-- Replaces the previously ad-hoc table created in Supabase dashboard.

-- 1. Create table (safe to re-run)
CREATE TABLE IF NOT EXISTS portfolio (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticker      TEXT NOT NULL,
  quantity    INTEGER NOT NULL DEFAULT 0,
  avg_cost    DOUBLE PRECISION,                     -- average entry cost per share
  market_value DOUBLE PRECISION,                     -- current market value (qty × last price)
  last_price  DOUBLE PRECISION,                     -- most recent close/quote
  unrealized_pnl   DOUBLE PRECISION,                -- (last_price - avg_cost) × quantity
  allocation_pct   DOUBLE PRECISION,                -- position as % of total portfolio
  vix_zone    TEXT,                                 -- VIX beta group label from screener
  bucket      TEXT NOT NULL DEFAULT 'existing',     -- trading bucket assignment
  snapshot_at TIMESTAMPTZ NOT NULL DEFAULT now(),   -- when this row was last updated
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2. Index for fast ticker lookups
CREATE INDEX IF NOT EXISTS idx_portfolio_ticker ON portfolio(ticker);

-- 3. Enable RLS — anon can read, service_role writes
ALTER TABLE portfolio ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_portfolio" ON portfolio;
CREATE POLICY "anon_select_portfolio" ON portfolio
  FOR SELECT
  TO anon
  USING (true);

-- 4. Enable realtime for live dashboard updates
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'portfolio'
  ) THEN
    ALTER publication supabase_realtime ADD TABLE portfolio;
  END IF;
END;
$$;