-- Equity Shortlist table: per-symbol Layer 2 M15 indicator snapshots.
-- Engine UPSERTs every 15 minutes. Frontend fetches via REST on-demand.
-- Row count = universe size (100-200), never grows.

CREATE TABLE IF NOT EXISTS equity_shortlist (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol          TEXT NOT NULL UNIQUE,                     -- e.g., "AAPL.US"
  current_price   DOUBLE PRECISION,                         -- Latest M15 close
  sma200          DOUBLE PRECISION,                         -- D1 SMA(200) from Layer 1
  price_vs_sma200_pct DOUBLE PRECISION,                     -- (price / sma200 - 1) * 100
  xgb_prob        DOUBLE PRECISION,                         -- XGBoost entry probability (0-1)
  prob_vs_threshold DOUBLE PRECISION,                       -- How close to threshold (prob - 0.65)
  rsi_14          DOUBLE PRECISION,                         -- RSI(14) on M15
  atr_pct         DOUBLE PRECISION,                         -- ATR(14) as % of price
  vwap_distance_pct DOUBLE PRECISION,                       -- Distance from VWAP %
  volume_zscore   DOUBLE PRECISION,                         -- Volume Z-score
  approved        BOOLEAN NOT NULL DEFAULT FALSE,           -- Passed Layer 1 (SMA200)?
  status          TEXT NOT NULL DEFAULT 'evaluating',        -- evaluating / ready / blocked / entered
  block_reason    TEXT,                                     -- Why not entered (if blocked)
  recent_snapshots JSONB,                                   -- Last 10 indicator snapshots [{ts, price, prob, rsi, atr_pct}]
  last_evaluated  TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_updated    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_equity_shortlist_status ON equity_shortlist(status);
CREATE INDEX IF NOT EXISTS idx_equity_shortlist_prob ON equity_shortlist(xgb_prob DESC);

-- RLS: anon can read
ALTER TABLE equity_shortlist ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_equity_shortlist" ON equity_shortlist;
CREATE POLICY "anon_select_equity_shortlist" ON equity_shortlist
  FOR SELECT
  TO anon
  USING (true);


-- Equity Activity table: significant engine events for live feed.
-- Engine INSERTs on key events only (~10-30/hr). Frontend subscribes via realtime.
-- Engine periodically trims to last 200 rows.

CREATE TABLE IF NOT EXISTS equity_activity (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type      TEXT NOT NULL,                            -- signal_fired / entry_blocked / entry_confirmed / exit_triggered / regime_change / engine_started / engine_paused / engine_resumed
  symbol          TEXT,                                     -- Ticker (nullable for engine/regime events)
  message         TEXT NOT NULL,                            -- Human-readable description
  detail_json     JSONB,                                    -- Extra structured data (prob, price, reason, etc.)
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_equity_activity_type ON equity_activity(event_type);
CREATE INDEX IF NOT EXISTS idx_equity_activity_created ON equity_activity(created_at DESC);

-- RLS: anon can read
ALTER TABLE equity_activity ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_equity_activity" ON equity_activity;
CREATE POLICY "anon_select_equity_activity" ON equity_activity
  FOR SELECT
  TO anon
  USING (true);

-- Enable realtime for live feed
ALTER publication supabase_realtime ADD TABLE equity_activity;